# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    environment: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      env:
        CKEY: ${{ secrets.CKEY }}
        CSEC:  ${{ secrets.CSEC }}
        AT:  ${{ secrets.AT }}
        ATS:  ${{ secrets.ATS }}
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm ci
    - run: node app.js vaccine --ckey ${CKEY} --csec ${CSEC} --at ${AT} --ats ${ATS}
